#!/usr/bin/env python3

import csv
import sys

def csv_to_markdown(input_file):
    # Open the CSV file
    with open(input_file, mode='r', encoding='utf-8') as csv_file:
        csv_reader = csv.reader(csv_file)
        
        # Read the headers
        headers = next(csv_reader)
        markdown_table = ["| " + " | ".join(headers) + " |"]
        
        # Add the separator line
        markdown_table.append("| " + " | ".join(["-" * len(h) for h in headers]) + " |")
        
        # Read the rows
        for row in csv_reader:
            markdown_table.append("| " + " | ".join(row) + " |")
        
        # Join the lines to form the final Markdown table
        return "\n".join(markdown_table)

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: ./csv2markdown <input_csv_file>")
    else:
        input_file = sys.argv[1]
        markdown_table = csv_to_markdown(input_file)
        print(markdown_table)
